<a href="https://colab.research.google.com/github/mawarqurnelia/python_datascience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

## Numpy Create Array

In [ ]:
#@title 0-D Array

var_array = np.array(42)

print(var_array)

42


In [ ]:
#@title 1-D Array

var_array = np.array([1, 2, 3, 4, 5])

print(var_array)

[1 2 3 4 5]


In [ ]:
var_array = np.ones(5)
print(var_array)

[1. 1. 1. 1. 1.]


In [ ]:
var_array = np.zeros(4)
print(var_array)

[0. 0. 0. 0.]


In [ ]:
var_array = np.random.random(6)
print(var_array)

[0.97680112 0.14286732 0.01884012 0.21165318 0.6878579  0.96800335]


In [ ]:
#@title 2-D Array

var_array = np.array([[1, 2, 3], [4, 5, 6]])

print(var_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#@title 3-D Array

var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(var_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#@title Check dimensi array

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#@title Create array range
#numpy.arange(start, stop, step)

var_array = np.arange(1, 20, 2)
print(var_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# create with reshape

var_array = np.arange(10).reshape((2, 5))
print(var_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# create numpy text

var_array = np.array(['apple', 'banana', 'cherry'])
print(var_array)

['apple' 'banana' 'cherry']


## Numpy Array Indexing

In [ ]:
#@title Akses indeks

# 1-D
var_array = np.array([85, 55, 40, 90])

# mengakses data pada array
print(var_array[3])

90


In [ ]:
# 2-D
var_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(var_array[1, 2])

8


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 2])

12


In [ ]:
#@title Operation indeks

var_array = np.array([1, 2, 3, 4])

print(var_array[2] + var_array[3])

7


In [ ]:
print(var_array[0] + var_array[2])

4


In [ ]:
#@title Slicing array

# 1-D
var_array = np.array([1, 2, 3, 4, 5, 6, 7])

print(var_array[3:])

[4 5 6 7]


In [ ]:
# 2-D
var_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var_array[0, 1:4])

[2 3 4]


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 0:2])

[10 11]


In [ ]:
#@title Iterating Arrays

var_array = np.array([1, 2, 3])

for x in var_array:
  print(x)

1
2
3


In [ ]:
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in var_array:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Numpy Array Join

In [ ]:
#@title Concatenate

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
var_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
var_array2 = np.array([[[4, 7, 9], [1, 6, 2]], [[3, 5, 8], [19, 10, 14]]])

arr = np.concatenate((var_array1, var_array2))
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 4  7  9]
  [ 1  6  2]]

 [[ 3  5  8]
  [19 10 14]]]


In [ ]:
#@title Stack

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# arr = np.stack((arr1, arr2))
# arr = np.hstack((arr1, arr2))
arr = np.vstack((arr1, arr2))
# arr = np.dstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Numpy Splitting

In [ ]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# 2-D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
newarr = np.array_split(arr, 2)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[1, 2, 3],
        [4, 5, 6]]])]


## Numpy Matriks

In [ ]:
matriks = [[1,2,3],
           [4,5,6],
           [7,8,9]]

matrik_np = np.array(matriks)
print(matrik_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#@title Operasi matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

matrik_b = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]])


hasil = matrik_a + matrik_b
print("Hasil Penjumlahan:")
print(hasil)

Hasil Penjumlahan:
[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [ ]:
hasil = matrik_a - matrik_b
print("Hasil Pengurangan:")
print(hasil)

Hasil Pengurangan:
[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [ ]:
# pangkat dengan power()

result_power = np.power(matrik_a, 2)
print("Hasil Perhitungan Pangkat (matrik_a pangkat 2):")
print(result_power)

Hasil Perhitungan Pangkat (matrik_a pangkat 2):
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# trigonometri dengan sin()

result_power = np.sin(matrik_a)
print("Hasil sin matrik_a:")
print(result_power)

Hasil sin matrik_a:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
#@title Transpose matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)


hasil = matrik_a.transpose()
print("\nMatrik kebalikan: ")
print(hasil)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrik kebalikan: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#@title Reshape matrik

matrik_a = np.array([1, 2, 3, 4, 5, 6])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

# mengubah ukran ke 3x2
hasil = matrik_a.reshape(3, 2)

print("\nMengubah ke 3x2: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[1 2 3 4 5 6]
Ukuran =  (6,)

Mengubah ke 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Ukuran =  (3, 2)


In [ ]:
#@title Matrik flatten

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

hasil = matrik_a.flatten()

print("\nMatrik setelah di-flatten: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ukuran =  (3, 3)

Matrik setelah di-flatten: 
[1 2 3 4 5 6 7 8 9]
Ukuran =  (9,)


## Numpy Statistik

In [ ]:
#@title rata-rata (mean)

data = np.array([12, 15, 18, 22, 30, 35, 40, 45, 55, 65])

mean = np.mean(data)
print("Rata-rata (mean):", mean)

Rata-rata (mean): 33.7


In [ ]:
#@title median

median = np.median(data)
print("Median:", median)

Median: 32.5


In [ ]:
#@title standard deviation

std_deviation = np.std(data)
print("Deviasi Standar (standard deviation):", std_deviation)

Deviasi Standar (standard deviation): 16.79315336677421


In [ ]:
#@title variansi (variance)

variance = np.var(data)
print("Variansi (variance):", variance)

Variansi (variance): 282.01


In [ ]:
#@title minimum dan maksimum

minimum = np.min(data)
maximum = np.max(data)
print("Nilai Minimum:", minimum)
print("Nilai Maksimum:", maximum)

Nilai Minimum: 12
Nilai Maksimum: 65


In [ ]:
#@title quartile

# Menghitung kuartil pertama (Q1) dan kuartil ketiga (Q3)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print("Kuartil Pertama (Q1):", q1)
print("Kuartil Ketiga (Q3):", q3)


# Menghitung rentang interkuartil (IQR)
iqr = q3 - q1
print("Rentang Interkuartil (IQR):", iqr)

Kuartil Pertama (Q1): 19.0
Kuartil Ketiga (Q3): 43.75
Rentang Interkuartil (IQR): 24.75


## Soal 1

Buat contoh :

* numpy array (1D, 2D, 3D)
* numpy join
* numpy split
* operasi matrik

In [ ]:
import numpy as np

**- NUMPY ARRAY (1D, 2D, 3D)**

In [ ]:
#NUMPY ARRAY (1D, 2D, 3D)
# 1D ARRAY - MEMBUAT ARRAY 1 DIMENSI
array_1d = np.array([10, 20, 30, 40, 50])
print("Array 1D:")
print(array_1d)

# 2D ARRAY - MEMBUAT ARRAY 2 DIMENSI
array_2d = np.array([[5, 10, 15], [20, 25, 30]])
print("\nArray 2D:")
print(array_2d)

# 3D ARRAY - MEMBUAT ARRAY 3 DIMENSI
array_3d = np.array([[[2, 4], [6, 8]], [[10, 12], [14, 16]]])
print("\nArray 3D:")
print(array_3d)


Array 1D:
[10 20 30 40 50]

Array 2D:
[[ 5 10 15]
 [20 25 30]]

Array 3D:
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


**- NUMPY JOIN**

In [ ]:
#NUMPY JOIN
#MENGGABUNGKAN DUA ARRAY 1D
array_1 = np.array([3, 6, 9])
array_2 = np.array([12, 15, 18])
joined_array = np.concatenate((array_1, array_2)) #MEMAKAI .CONCATENATE
print("Joined Array 1D:", joined_array)

Joined Array 1D: [ 3  6  9 12 15 18]


**- NUMPY SPLIT**

In [ ]:
#NUMPY SPLIT
#MEMBAGI JOINED_ARRAY MENJADI 3 BAGIAN
split_array = np.array_split(joined_array, 3)
print("Split Array 1D:", split_array)

Split Array 1D: [array([3, 6]), array([ 9, 12]), array([15, 18])]


**- OPERASI MATRIKS (PENJUMLAHAN DAN PENGURANGAN)**





In [ ]:
#OPERASI MATRIKS
matriks1 = np.array([[2, 3], [4, 5]])
matriks2 = np.array([[6, 7], [8, 9]])

#PENJUMLAHAN MATRIKS 2D
hasil = matriks1 + matriks2
print("Hasil Penjumlahan:")
print(hasil)
# #CARA LAIN DENGAN .ADD
# matrix_sum = np.add(matriks1, matriks2)
# print("Hasil Penjumlahan:")
# print(matrix_sum)

#PENGURANGAN MATRIKS 2D
hasil = matriks1 - matriks2
print("\nHasil Pengurangan:")
print(hasil)
# #CARA LAIN DENGAN .SUBTRACT
# matrix_subtr = np.subtract(matriks1, matriks2)
# print("Hasil Pengurangan:")
# print(matrix_subtr)

Hasil Penjumlahan:
[[ 8 10]
 [12 14]]

Hasil Pengurangan:
[[-4 -4]
 [-4 -4]]


## Soal 2

* Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30
* Kemudian lakukan flatten
* cari nilai statistik (mean, median, dsb)

**- MEMBUAT ARRAY**

In [ ]:
#MEMBUAT ARRAY 3x4 DENGAN RANGE ANGKA 10-30
matriks = np.arange(10, 22).reshape(3, 4) #MATRIKS 3X4 BERISI 12 ELEMEN SAJA SEHINGGA DIPILIH 10-22 DARI RANGE 10-30
print("Matriks 3x4:")
print(matriks)

Matriks 3x4:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


**- MELAKUKAN FLATTEN**

In [ ]:
# MELAKUKAN FLATTEN
flattened_matriks = matriks.flatten()
print("Matriks Setelah Flatten:")
print(flattened_matriks)

Matriks Setelah Flatten:
[10 11 12 13 14 15 16 17 18 19 20 21]


**- MENGHITUNG STATISTIK**

In [ ]:
# MENGHITUNG STATISTIK
mean_value = np.mean(flattened_matriks)         #RATA-RATA
median_value = np.median(flattened_matriks)     #MEDIAN
std_value = np.std(flattened_matriks)           #STANDAR DEVIASI
var_value = np.var(flattened_matriks)           #VARIANSI
min_value = np.min(flattened_matriks)           #NILAI MINIMUM
max_value = np.max(flattened_matriks)           #NILAI MAKSIMUM
q1_value = np.percentile(flattened_matriks, 25) #KUARTIL1
q3_value = np.percentile(flattened_matriks, 75) #KUARTIL3
iqr = q3_value - q1_value                       #RENTANG IQR

# MENAMPILKAN NILAI STATISTIK
print("Statistik Matriks:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Min: {min_value}")
print(f"Max: {max_value}")
print(f"Standar Deviasi: {std_value}")
print(f"Variansi: {var_value}")
print(f"Kuartil Pertama (Q1): {q1_value}")
print(f"Kuartil Ketiga (Q3): {q3_value}")
print(f"Rentang Interkuartil (IQR): {iqr}")

Statistik Matriks:
Mean: 15.5
Median: 15.5
Min: 10
Max: 21
Standar Deviasi: 3.452052529534663
Variansi: 11.916666666666666
Kuartil Pertama (Q1): 12.75
Kuartil Ketiga (Q3): 18.25
Rentang Interkuartil (IQR): 5.5
